name: Build LaTeX document
on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md # Should never be edited anyway
      - .gitignore
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  build_latex:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile main-german.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: root.tex
          compiler: pdflatex
          args:
      - name: Compile Bibliography file
        uses: dante-ev/latex-action@latest
        with:
          root_file: root
          compiler: biber
          args:
      - name: Generate PDF file
        uses: dante-ev/latex-action@latest
        with:
          root_file: root.tex
          compiler: pdflatex
          args:
      - name: Save PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: root.pdf
